
##Регистрация пользователя
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name":  "Олег",
"email": "test3@test.ru",
  "password": "testtest"
}

###

##Авторизация
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "test@test.ru",
  "password": "testtest"
}

###
PATCH http://localhost:3000/users/me
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTNjNjJhMWJkNzcyNjVmNWRmYjE4MzAiLCJpYXQiOjE2MzEzNDgzMjQsImV4cCI6MTYzMTk1MzEyNH0.5bchkbU14oXiAjSWq_kGWrYjobq5Ql1TkN60KojfoiY


{
"email": "test1@test.ru",
"name": "Федор"
}


###Удаление карточки
DELETE http://localhost:3000/movies/613dc064874b8a58449cb090
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTNjNjJhMWJkNzcyNjVmNWRmYjE4MzAiLCJpYXQiOjE2MzEzNDgzMjQsImV4cCI6MTYzMTk1MzEyNH0.5bchkbU14oXiAjSWq_kGWrYjobq5Ql1TkN60KojfoiY

###Добавление карточки
POST http://localhost:3000/movies
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTNjNjJhMWJkNzcyNjVmNWRmYjE4MzAiLCJpYXQiOjE2MzEzNDgzMjQsImV4cCI6MTYzMTk1MzEyNH0.5bchkbU14oXiAjSWq_kGWrYjobq5Ql1TkN60KojfoiY

{
        "id": 1,
        "nameRU": "«123 Стоунз» в изгнании",
        "nameEN": "Stones in Exile",
        "director": "Стивен Кайак ",
        "country": "США",
        "year": "2010",
        "duration": 61,
        "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
        "image": "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/arkhyz.jpg",
  "thumbnail": "https://pictures.s3.yandex.net/frontend-developer/cards-compressed/arkhyz.jpg",
  "trailer": "https://www.youtube.com/watch?v=UXcqcdYABFw"
}
###Запрос всех сохраненных фильмов
GET http://localhost:3000/movies
Accept: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTNjNjJhMWJkNzcyNjVmNWRmYjE4MzAiLCJpYXQiOjE2MzEzNDgzMjQsImV4cCI6MTYzMTk1MzEyNH0.5bchkbU14oXiAjSWq_kGWrYjobq5Ql1TkN60KojfoiY


###

GET http://localhost:3000/users/me
Accept: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTNjNjJhMWJkNzcyNjVmNWRmYjE4MzAiLCJpYXQiOjE2MzEzNDgzMjQsImV4cCI6MTYzMTk1MzEyNH0.5bchkbU14oXiAjSWq_kGWrYjobq5Ql1TkN60KojfoiY


###

